apiVersion: v2
appVersion: "1.6.0-rc1"
description: A Helm chart for ArgoCD, a declarative, GitOps continuous delivery tool for Kubernetes.
name: argo-cd
version: 2.3.5
home: https://github.com/argoproj/argo-helm
icon: https://raw.githubusercontent.com/argoproj/argo/master/docs/assets/argo.png
keywords:
  - argoproj
  - argocd
  - gitops
maintainers:
  - name: alexec
  - name: alexmt
  - name: jessesuen
  - name: seanson
